apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: <base64-encoded-ca-cert>
      server: https://<cluster-api-server-address>
    name: my-cluster
contexts:
  - context:
      cluster: my-cluster
      user: my-user
    name: my-context
current-context: my-context
kind: Config
preferences: {}
users:
  - name: my-user
    user:
      client-certificate-data: <base64-encoded-client-cert>
      client-key-data: <base64-encoded-client-key>


